export const Colors = {
  background: '#FAFAF7',
  surface: '#FFFFFF',
  textPrimary: '#1A1A18',
  textSecondary: '#6B6B64',
  textTertiary: '#6B6B64',
  accent: '#B84B2A',
  accentLight: '#FFF0EB',
  success: '#3A8A5C',
  successLight: '#E8F5ED',
  warning: '#C68B2C',
  warningLight: '#FFF8EC',
  border: '#E8E8E3',
  tabInactive: '#6B6B64',
  tabActive: '#B84B2A',
} as const;
